version: '3.8'
services:
  node:
    image: prom/node-exporter
    ports:
      - "9100:9100"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP="false"
      - GF_USERS_ALLOW_ORG_CREATE="false"
    ports:
        - "3000:3000"
